### ISSUE TITLE
Issue with Swift 3.0 beta 

### ISSUE THREAD

**Issue by gavinb80** [calebkleveter/SwiftDropdownMenu#3]
Hi,

I am getting a error with 3 bits of code when compiling in Xcode 8 beta 6:

```
    func prepareForSegue(_ segue: UIStoryboardSegue, sender: AnyObject) {
        if let identifier = segue.identifier {
            self.currentSegueIdentifier = identifier
            super.prepare(for: segue, sender: sender)
        }
    }
```

gives error Method 'prepareForSegue(_:sender:)' with Objective-C selector 'prepareForSegue:sender:' conflicts with method 'prepare(for:sender:)' from superclass 'UIViewController' with the same Objective-C selector

```
    func shouldPerformSegueWithIdentifier(_ identifier: String, sender: AnyObject) -> Bool {
        if self.currentSegueIdentifier.isEqual(identifier) {
            //Dont perform segue, if visible ViewController is already the destination ViewController
            return false
        }
        return true
    }
```

gives error  Method 'shouldPerformSegueWithIdentifier(_:sender:)' with Objective-C selector 'shouldPerformSegueWithIdentifier:sender:' conflicts with method 'shouldPerformSegue(withIdentifier:sender:)' from superclass 'UIViewController' with the same Objective-C selector

and 

```
    func setTrianglePlacement(_ trianglePlacementVal: Float) {
        trianglePlacement = trianglePlacementVal
    }
```

gives error Method 'setTrianglePlacement' with Objective-C selector 'setTrianglePlacement:' conflicts with setter for 'trianglePlacement' with the same Objective-C selector

I dont suppose you have a fix for these?

**Comment by calebkleveter** [comment]
It looks like I fixed those issues but forgot to push them to CocoaPods. I am working on pushing it now, so check back soon!

**Comment by calebkleveter** [comment]
I got version 2.0 up. Try updating and see how it works!

**Comment by gavinb80** [comment]
many thanks, I shall try this shortly :+1:

**Comment by gavinb80** [comment]
Got it working perfect thanks.  Do you have a working sample project? I cannot get the Example to install correctly?

*edit - for context, I can get a menu to show up, but the first time I use it, I have to click it twice before it shows

**Comment by calebkleveter** [comment]
I am going to make a couple of changes to the Pod for it to work. I found some issues while I was working on the example project, which you can find [here](https://github.com/calebkleveter/CKDropdownMenu-Example) (The dropdown works, but the segues don't). Hope this answer it!
